---
name: Task - Test Bridge

on:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test_bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup show

      - uses: Swatinem/rust-cache@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # ---------------------------------------------------
      # workaround : https://github.com/asdf-vm/actions/issues/562
      # asdf installation
      - name: Detect ASDF .tool-versions file in repo
        shell: bash
        id: detect_tool_versions_file
        run: |
          if [ -s .tool-versions ]; then
          echo "exists=1" >> $GITHUB_OUTPUT
          fi

      - name: ASDF install tools
        if: ${{ steps.detect_tool_versions_file.outputs.exists == '1' }}
        uses: asdf-vm/actions/install@6a442392015fbbdd8b48696d41e0051b2698b2e4
      # ---------------------------------------------------

      - name: Setup build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libudev-dev protobuf-compiler
      - uses: rui314/setup-mold@v1
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.2"
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Ganache
        run: |
          npm install -g ganache@7.9.0
          ganache --version

      - name: Install Solc
        run: |
          pip install solc-select
          solc-select install 0.8.19
          solc-select use 0.8.19
          solc --version

      - name: Checkout Madara
        uses: actions/checkout@v4
        with:
          repository: madara-alliance/madara
          ref: "d188aa91efa78bcc54f92aa1035295fd50e068d2"
          path: madara

      - name: Move Madara Devnet config
        working-directory: madara
        run: |
          ls
          mv configs/presets/devnet.yaml ../bin/devnet.yaml

      - name: Build Madara
        working-directory: madara
        run: |
          cargo build
          mv target/debug/madara ../bin/madara
          cd ..

      - name: Run anvil
        run: |
          anvil &

      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      - name: Clean workspace
        run: |
          cargo llvm-cov clean --workspace

      - name: Run llvm-cov
        run: |
          git submodule update --init --recursive
          make artifacts-linux
          RUST_BACKTRACE=1 RUST_LOG=debug cargo test -- deposit_tests_both_bridges --nocapture

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: lcov.info
          debug: true

      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: lcov.info
          debug: true
